name: CI/CD

on:
  push:
    branches:
      - main
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-docker@v1
        

      - name: Pull Docker nginx image
        run: docker pull nginx:latest

      - name: Run tests
        run: docker run -d nginx:latest

      - name: Deploy to production
        if: github.ref == 'refs/heads/main'
        run: |
          echo this is main site
          # Example: Deploy to a hosting platform or cloud provider

      - name: Deploy to development environment
        if: github.ref == 'refs/heads/development'
        run: |
          echo this is dev site
          # Example: Deploy to a staging environment or development server
