name: CI/CD

on:
  push:
    branches:
      - main
      - development

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to production
        if: github.ref == 'refs/heads/main'
        run: |
          # Restart Docker Service 
           cd /root/odoo/ && docker compose down &&  docker compose up -d
           echo 'This is main site'

      - name: Deploy to development environment
        if: github.ref == 'refs/heads/development'
        run: |
          # Restart Docker Service
          echo 'THIS IS DEV Branch'
