name: CI/CD

on:
  push:
    branches:
      - main
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to production
        if: github.ref == 'refs/heads/main'
        run: |
          echo this is main site
          # Example: Deploy to a hosting platform or cloud provider

      - name: Deploy to development environment
        if: github.ref == 'refs/heads/development'
        run: |
          echo this is development  site
          # Example: Deploy to a staging environment or development server
