name: My-FIRST-Actions 111

on: 
  push:
    branches: 
      - main
      

jobs:
  my_testing_docker:
    runs-on: self-hosted
    
    steps:
     - uses: actions/checkout@v2
     - name: Print Hello Message
       run: |
        echo "Hello World from Testing Jobs 123 "
        #docker pull httpd
        cd /root/odoo/ && docker compose up -d
       
       
  
