name: My-FIRST-Actionsassssssssssssssssssss

on:[workflow_dispatch] 

jobs:
    #runs-on: self-hosted
  runs-on: ubuntu-latest
  steps:
    - run: |
       docker pull httpd
       docker run -d --name GIT-APACHE -p 8080:80 -d httpd
    - run: echo "ALL GOOD"
