name: My-FIRST-Actions

on: 
  push:
    branches: 
      - main
      

jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
     - name: Print Hello Message
       run: |
        echo "Hello World from Testing Jobs 123 "
       
       
  
